# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Cognitive Robotics Lab
university: University of Arkansas
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Focus on teaching robots how to build maps, navigate, and plan motions inspired by human cognition. The ultimate goal is to facilitate human-robot interaction naturally.
# url: http://wwww.cogniboticslab.org
link: http://www.cogniboticslab.org

# Build settings
# theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
